[package]
name = "nearmypostcode_packer"
version = "0.1.0"
authors = ["Lex Bailey"]
edition = "2021"

[dependencies]
time = "0.3.41"
geo = "0.29.3"
csv = "1.3.1"
clap = {version="4.5.41", features=["cargo"]}
